### ISSUE TITLE
crash of ui_list node

### ISSUE THREAD

**Issue by jo-elektro** [node-red-hitachi/ui_list#2]
Hi,
I just added the UI_list node to my node red test rig running 0.18.4 and also added the example with the 3 injects. 
But the list does not show up in the dashboard and the log of node red gives the following messages: 

29 Oct 10:47:44 - [info] Installed module: node-red-contrib-ui_list
29 Oct 10:47:44 - [info] Added node types:
29 Oct 10:47:44 - [info]  - node-red-contrib-ui_list:ui_list
29 Oct 10:48:15 - [info] Stopping modified flows
29 Oct 10:48:15 - [info] Stopped modified flows
29 Oct 10:48:15 - [info] Starting modified flows
TypeError: RED.require is not a function
at new ListNode (/home/pi/.node-red/node_modules/node-red-contrib-ui_list/ui_list.js:75:26)
at createNode (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:305:18)
at Flow.start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:89:35)
at start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:307:29)
at /usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:144:21
at tryCatchReject (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:845:30)
at runContinuation1 (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:804:4)
at Fulfilled.when (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:592:4)
at Pending.run (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:483:13)
at Scheduler._drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:62:19)
at Scheduler.drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:27:9)
at _combinedTickCallback (internal/process/next_tick.js:73:7)
at process._tickCallback (internal/process/next_tick.js:104:9)
29 Oct 10:48:15 - [error] [ui_list:ba2e06c2.bf95f] TypeError: Cannot read property 'push' of undefined
29 Oct 10:48:15 - [info] Started modified flows

Greetings,

Jo

**Comment by HiroyasuNishiyama** [comment]
Hi, thank you for trying `ui_list` node.
`ui_list` uses `RED.require` API introduced from Node-RED 0.19.
Could you please try with latest version of Node-RED & Node-RED dashboard.

**Comment by jo-elektro** [comment]
Hi,
Thank you for your fast answer but i replicated this on a IBM bluemix cloud with Node-red 0.19.4 running and the same fault is reported. 
"TypeError: Cannot read property 'push' of undefined"

**Comment by HiroyasuNishiyama** [comment]
Sorry, I do not have access to Node-RED 0.19.4 on IBM bluemix.
Is there any other output log from Node-RED?

**Comment by jo-elektro** [comment]
I am also still new to the iBM cloud stuff but the debug window only said "TypeError: Cannot read property 'push' of undefined". 
I also updated my node red on the raspberry to the latest 0.19.4 and checked that dashboard is up to date but also here the ui_list node fails with the issue about the push property being undefined. 
What environment did you test it?

**Comment by HiroyasuNishiyama** [comment]
I am testing `ui_list` on MacOS and Windows.
Can I ask you when the `TypeError` message is shown on debug window?
Is installation and deploument of the node is successful?

**Comment by HiroyasuNishiyama** [comment]
Hi, I have been able to reproduced the error.
After installing dashboard and `ui_list`,   restarting node-red is needed.
Could you try it?

**Comment by jo-elektro** [comment]
It shows after deployment of the flow. 
Here is the log after deploying with the ui_list example 

{ Error: Cannot find module '../../../../../../../../home/pi/.node-red/node_modules/node-red-dashboard'
at Function.Module._resolveFilename (module.js:470:15)
at Function.Module._load (module.js:418:25)
at Module.require (module.js:498:17)
at require (internal/module.js:20:19)
at Object.requireModule [as require] (/usr/lib/node_modules/node-red/red/runtime/nodes/registry/loader.js:69:16)
at new ListNode (/home/pi/.node-red/node_modules/node-red-contrib-ui_list/ui_list.js:75:26)
at createNode (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:305:18)
at Flow.start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:89:35)
at start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:328:29)
at /usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:164:25
at process._tickCallback (internal/process/next_tick.js:109:7) code: 'MODULE_NOT_FOUND' }
30 Oct 15:52:23 - [error] [ui_list:cbcb7f13.ac9a28] TypeError: Cannot read property 'push' of undefined

**Comment by jo-elektro** [comment]
ok. i'll do a restart. Just a moment.

**Comment by jo-elektro** [comment]
Nop. I restarted with the example already in place but the error persists. 
Am i missing something in my node red config? Some dependency?  

I did notice that my dashboard is version 2.9.1 and it could be upgraded to 2.10.1 but I get some npm error about a json package and it fails to update. Not sure if this related.

**Comment by HiroyasuNishiyama** [comment]
Can I see the error message?

**Comment by jo-elektro** [comment]
Hold on. I am doing some clean up and running the install/upgrade script. THis might take 15 to 20 minutes
I did not capture the npm error about the dashboard update.

**Comment by jo-elektro** [comment]
It working! 
I am not sure if it was because the version of dashboard was not up to date or that i had some inconsistency in my setup which has been corrected with running the node red upgrade script over it. 
I do apologize for the confusion and would like to thank you very much for your assistance and this very useful node you have produced. 
This was one of the items which were missing in opinion. 

Greetings,

Jo
